name: Build and Deploy to Azure Static Web App

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the app
        run: |
          npm install
          npm run build

      - name: Deploy to Azure Static Web App
        uses: azure/static-web-apps-deploy-action@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: "/"
          output_location: "build"
